name: ClippyTyper
options:
  deploymentTarget:
    macOS: '13.0'
packages:
  ClippyTyperPackage:
    path: ../
targets:
  ClippyTyper:
    type: application
    platform: macOS
    info:
      path: xcode/Info.plist
      properties:
        CFBundleIdentifier: com.clippytyper.app
        CFBundleName: ClippyTyper
        CFBundleShortVersionString: 0.1.1
        CFBundleVersion: 2
        LSBackgroundOnly: true
        LSUIElement: true
        CFBundleURLTypes:
          - CFBundleURLName: clippytyper
            CFBundleURLSchemes: [clippytyper]
    sources:
      - path: ../Sources/ClippyTyperApp
    dependencies:
      - package: ClippyTyperPackage
        product: ClippyTyperCore
      - package: ClippyTyperPackage
        product: ClippyTyperPreferences
      - package: ClippyTyperPackage
        product: ClippyTyperAppSupport
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
  ClippyTyperUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: xcode/UITests
    dependencies:
      - target: ClippyTyper
schemes:
  ClippyTyper:
    build:
      targets:
        ClippyTyper: all
    test:
      targets: [ClippyTyperUITests]
    run:
      askForAppToLaunch: false
